package(default_visibility = ["//visibility:public"])

cc_library(
	name = "sim",
	srcs = [
		"sim.cpp",
	],
	hdrs = [
		"sim.h",
	],
	deps = [
		"//src/vehicles:simple_car",
		"//src/roads:roads",
	],
)
