
package(default_visibility = ["//visibility:public"])

cc_library(
	name = "basic_planner",
	srcs = [
		"basic_ai.c",
	],
	hdrs = [
		"basic_ai.h",
	],
	deps = [
		"//src/common:common",
		"//src/vehicles:simple_car",
	],
)
