cc_binary(
	name = "avsim",
	srcs = [
		"main.c",
	],
	deps = [
		"//src/common:common",
		"//src/visualization:sdl_vis",
		"//src/simulator:sim",
		"//src/roads:roads",
		"//src/vehicles:simple_car",
		"//src/planner:basic_planner",
	],
)
