cc_binary(
	name = "avsim",
	srcs = [
		"main.cpp",
	],
	deps = [
		"//src/common:common",
		"//src/visualization:vis2d",
		"//src/simulation:sim",
		"//src/roads:roads",
		"//src/vehicles:vehicles",
		"//src/planner:basic_planner",
	],
)
