#pragma once


#define CFG_TICK_SLP_US (1000*10)
#define CFG_TICKS_PER_S (1000*1000 / CFG_TICK_SLP_US)
#define CFG_NUM_CARS (2)
#define CFG_SPACE_SCALE (1000)

/* CAR PARAMS */
#define CFG_CAR_MIN_LEN_M (4)
#define CFG_CAR_MAX_LEN_M (4)
#define CFG_CAR_MIN_TOP_SPD_MS (15)
#define CFG_CAR_MAX_TOP_SPD_MS (25)
#define CFG_CAR_MIN_SPD_MS (0)
#define CFG_CAR_MAX_SPD_MS (CFG_CAR_MAX_TOP_SPD_MS)


/* SINGLE ROAD SCENARIO SETTINGS */
#define CFG_SINGLE_ROAD
#ifdef CFG_SINGLE_ROAD

#define CFG_SINGLE_NUM_LANES 4
#define CFG_SINGLE_LEN_M 200

#endif

