package(default_visibility = ["//visibility:public"])

cc_library(
	name = "roads",
	srcs = [
		"loop.c",
	],
	hdrs = [
		"loop.h",
	],
	deps = [
		"//src/vehicles:simple_car",
		"//src/common:common",
	]
)
